package com.jasonzou.retrofitdemo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jasonzou.retrofitdemo.bean.IMConversationState;

import com.jasonzou.retrofitdemo.greendao.IMConversationStateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig iMConversationStateDaoConfig;

    private final IMConversationStateDao iMConversationStateDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        iMConversationStateDaoConfig = daoConfigMap.get(IMConversationStateDao.class).clone();
        iMConversationStateDaoConfig.initIdentityScope(type);

        iMConversationStateDao = new IMConversationStateDao(iMConversationStateDaoConfig, this);

        registerDao(IMConversationState.class, iMConversationStateDao);
    }
    
    public void clear() {
        iMConversationStateDaoConfig.clearIdentityScope();
    }

    public IMConversationStateDao getIMConversationStateDao() {
        return iMConversationStateDao;
    }

}
